datagrid:
    tasks-grid:
        source:
            type: orm
            acl_resource: ~ #orocrm_task_view
            query:
                select:
                    - task.id
                    - task.subject
                    - task.description
                    - task.dueDate
                    - taskPriority.title as priority
                    - assignedTo.username as assignee
                    - assignedTo.id as assigneeId
                    - owner.username as reporter
                    - owner.id as reporterId
                    - task.createdAt
                    - task.updatedAt
                from:
                    - { table: %orocrm_task.entity.class%, alias: task }
                join:
                    left:
                        - { join: task.taskPriority, alias: taskPriority }
                        - { join: task.assignedTo, alias: assignedTo }
                        - { join: task.owner, alias: owner }
        columns:
            subject:
                type: twig
                label: orocrm.task.subject.label
                frontend_type: html
                template: OroCRMTaskBundle:Task:Datagrid/Property/subject.html.twig
            dueDate:
                label: orocrm.task.dueDate.label
                frontend_type: datetime
            priority:
                label: orocrm.task.taskPriority.label
            assignee:
                type: twig
                label: orocrm.task.assignedTo.label
                frontend_type: html
                template: OroCRMTaskBundle:Task:Datagrid/Property/assignee.html.twig
            reporter:
                type: twig
                label: orocrm.task.owner.label
                frontend_type: html
                template: OroCRMTaskBundle:Task:Datagrid/Property/reporter.html.twig
            createdAt:
                label:   orocrm.task.createdAt.label
                frontend_type: datetime
            updatedAt:
                label:   orocrm.task.updatedAt.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_task_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_task_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      orocrm_api_delete_task
                params:     [ id ]
        sorters:
            columns:
                subject:
                    data_name: task.subject
                dueDate:
                    data_name: task.dueDate
                priority:
                    data_name: priority
                assignee:
                    data_name: assignee
                reporter:
                    data_name: reporter
                createdAt:
                    data_name: task.createdAt
                updatedAt:
                    data_name: task.updatedAt
            default:
                createdAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                subject:
                    type:      string
                    data_name: task.subject
                dueDate:
                    type:      datetime
                    data_name: task.dueDate
                priority:
                    type:      string
                    data_name: priority
                assignee:
                    type:      string
                    data_name: assignee
                reporter:
                    type:      string
                    data_name: reporter
                createdAt:
                    type:      datetime
                    data_name: task.createdAt
                updatedAt:
                    type:      datetime
                    data_name: task.updatedAt
        actions:
            view:
                type: navigate
                acl_resource: orocrm_task_view
                label: orocrm.task.datagrid.view
                icon: user
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: orocrm_task_update
                label: orocrm.task.datagrid.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: orocrm_task_delete
                label: orocrm.task.datagrid.delete
                icon: trash
                link: delete_link
        options:
            entityHint: task
            export: true

    account_tasks_grid:
        extend: tasks-grid

    account_tasks_grid:
        extend: tasks-grid
