datagrid:
    tasks-grid:
        source:
            type: orm
            acl_resource: orocrm_task_view
            query:
                select:
                    - task.id
                    - task.subject
                    - task.description
                    - task.dueDate
                    - taskPriority.label as priorityLabel
                    - assignedTo.username as assignee
                    - assignedTo.id as assigneeId
                    - owner.username as reporter
                    - owner.id as reporterId
                    - task.createdAt
                    - task.updatedAt
                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %orocrm_task.entity.class%, alias: task }
                join:
                    left:
                        - { join: task.taskPriority, alias: taskPriority }
                        - { join: task.assignedTo, alias: assignedTo }
                        - { join: task.owner, alias: owner }
                        - { join: task.workflowStep, alias: workflowStep }
        columns:
            subject:
                label: orocrm.task.subject.label
            dueDate:
                label: orocrm.task.dueDate.label
                frontend_type: datetime
            workflowStepLabel:
                label: orocrm.task.workflowStep.label
            priorityLabel:
                label: orocrm.task.taskPriority.label
            assignee:
                type: twig
                label: orocrm.task.assignedTo.label
                frontend_type: html
                template: OroCRMTaskBundle:Task:Datagrid/Property/assignee.html.twig
            reporter:
                type: twig
                label: orocrm.task.owner.label
                frontend_type: html
                template: OroCRMTaskBundle:Task:Datagrid/Property/reporter.html.twig
            createdAt:
                label:   orocrm.task.createdAt.label
                frontend_type: datetime
            updatedAt:
                label:   orocrm.task.updatedAt.label
                frontend_type: datetime
        sorters:
            columns:
                subject:
                    data_name: task.subject
                dueDate:
                    data_name: task.dueDate
                priorityLabel:
                    data_name: taskPriority.order
                assignee:
                    data_name: assignee
                reporter:
                    data_name: reporter
                createdAt:
                    data_name: task.createdAt
                updatedAt:
                    data_name: task.updatedAt
            default:
                dueDate: ASC
                priorityLabel: ASC
        filters:
            columns:
                subject:
                    type:      string
                    data_name: task.subject
                dueDate:
                    type:      datetime
                    data_name: task.dueDate
                priorityLabel:
                    type:      string
                    data_name: priorityLabel
                assignee:
                    type:      string
                    data_name: assignee
                reporter:
                    type:      string
                    data_name: reporter
                createdAt:
                    type:      datetime
                    data_name: task.createdAt
                updatedAt:
                    type:      datetime
                    data_name: task.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_task_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_task_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      orocrm_api_delete_task
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  orocrm_task_view
                label:         View
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  orocrm_task_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  orocrm_task_delete
                label:         Delete
                icon:          trash
                link:          delete_link

    task-account-tasks-grid:
        extend: tasks-grid
        source:
            query:
                where:
                      and:
                        - task.relatedAccount = :accountId

    task-contact-tasks-grid:
        extend: tasks-grid
        source:
            query:
                where:
                      and:
                        - task.relatedContact = :contactId

    task-user-tasks-grid:
        extend: tasks-grid
        source:
            query:
                where:
                      and:
                        - task.assignedTo = :userId
