oro_menu_config:
    items:
        task_list:
            label: 'orocrm.task.entity_plural_label'
            route: 'orocrm_task_index'
            extras:
                position: 10
                routes: ['orocrm_task_*']
                description: 'orocrm.task.menu.task_list.description'

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        task_list: ~

oro_titles:
    orocrm_task_index: ~
    orocrm_task_view: '%%entity.subject%%'
    orocrm_task_create: oro.ui.create_entity
    orocrm_task_update: '%%entity.subject%% - Edit'
