placeholders:
    oro_reminder_reminder_templates:
        items:
            task_reminder_template: ~

    view_navButtons_before:
        items:
            create_task_user_button: ~

    orocrm_user_tasks:
        items:
            orocrm_user_tasks_grid: ~

items:
    task_reminder_template:
        template: OroCRMTaskBundle:Task:reminderTemplate.html.twig

    create_task_user_button:
        template: OroCRMTaskBundle:Entities:createUserTaskButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

    orocrm_task_activity_button:
        template: OroCRMTaskBundle:Task:activityButton.html.twig
        acl: orocrm_task_create
