placeholders:
    oro_reminder_reminder_templates:
        items:
            task_reminder_template: ~

    orocrm_user_tasks:
        items:
            orocrm_user_tasks_grid: ~

items:
    task_reminder_template:
        template: OroCRMTaskBundle:Task:reminderTemplate.html.twig

    orocrm_add_task_button:
        template: OroCRMTaskBundle:Task:activityButton.html.twig
        acl: orocrm_task_create
        data:
            label: @orocrm_task.label_provider.action_button->getLabel($entity$)
            widget_title: @orocrm_task.label_provider.action_button->getWidgetTitle($entity$)

    orocrm_add_task_link:
        template: OroCRMTaskBundle:Task:activityLink.html.twig
        acl: orocrm_task_create
        data:
            label: @orocrm_task.label_provider.action_button->getLabel($entity$)
            widget_title: @orocrm_task.label_provider.action_button->getWidgetTitle($entity$)
