placeholders:
    orocrm_contact_tasks:
        items:
            orocrm_contact_tasks_grid: ~
    orocrm_user_tasks:
            items:
                orocrm_user_tasks_grid: ~

items:
    orocrm_contact_tasks_grid:
        template: OroCRMTaskBundle:Task:contactTasksInfo.html.twig
    orocrm_user_tasks_grid:
        template: OroCRMTaskBundle:Task:userTasksInfo.html.twig

