parameters:
    #entity
    orocrm_task.entity.class:         OroCRM\Bundle\TaskBundle\Entity\Task

    #form
    orocrm_task.form.type.task.class: OroCRM\Bundle\TaskBundle\Form\Type\TaskType

services:
    orocrm_task.form.type.task:
        class: %orocrm_task.form.type.task.class%
        tags:
            - { name: form.type, alias: orocrm_task }
