parameters:
    #entity
    orocrm_task.entity.class:         OroCRM\Bundle\TaskBundle\Entity\Task

    #form
    orocrm_task.form.type.task.class:     OroCRM\Bundle\TaskBundle\Form\Type\TaskType
    orocrm_task.form.type.api_task.class: OroCRM\Bundle\TaskBundle\Form\Type\TaskApiType

    orocrm_task.task.manager.api.class:   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    orocrm_task.handler.task.class:       OroCRM\Bundle\TaskBundle\Form\Handler\TaskHandler
services:
    orocrm_task.form.type.task:
        class: %orocrm_task.form.type.task.class%
        tags:
            - { name: form.type, alias: orocrm_task }

    orocrm_task.form.type.api_task:
        class: %orocrm_task.form.type.api_task.class%
        tags:
            - { name: form.type, alias: orocrm_task_api }

    #data grid events
    orocrm_task.event_listener.account_tasks_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
            - 'accountId'
            - @oro_datagrid.datagrid.request_params
            - false
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.task-account-tasks-grid, method: onBuildAfter }

    orocrm_task.event_listener.contact_tasks_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
            - 'contactId'
            - @oro_datagrid.datagrid.request_params
            - false
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.task-contact-tasks-grid, method: onBuildAfter }

    orocrm_task.event_listener.user_tasks_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
            - 'userId'
            - @oro_datagrid.datagrid.request_params
            - false
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.task-user-tasks-grid, method: onBuildAfter }

    orocrm_task.task.manager.api:
        class: %orocrm_task.task.manager.api.class%
        arguments:
            - %orocrm_task.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_task.form.handler.task.api:
        class: %orocrm_task.handler.task.class%
        scope: request
        arguments:
            - @orocrm_account.form.account.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }