parameters:
    orocrm_task.entity.class:         OroCRM\Bundle\TaskBundle\Entity\Task

    orocrm_task.listener.datagrid.activity.class:   OroCRM\Bundle\TaskBundle\EventListener\Datagrid\ActivityGridListener

services:
    orocrm_task.listener.datagrid.activity:
        class: %orocrm_task.listener.datagrid.activity.class%
        arguments:
            - @oro_activity.manager
            - @oro_entity.routing_helper
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.activity-task-grid, method: onBuildAfter }
