OroCRM\Bundle\TaskBundle\Entity\Task:
    properties:
        subject:
            - NotBlank: ~
            - Length:
                max: 255
        dueDate:
            - NotBlank: ~
            - DateTime: ~
#        priority:
#            - NotBlank: ~
        assignedTo:
            - NotBlank: ~
        owner:
            - NotBlank: ~